package com.optitrack.repository;

import com.optitrack.model.entity.User;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.Optional;

/**
 * Purpose: Data access layer for User entities.
 * 
 * Design Note: Extends JpaRepository to provide out-of-the-box CRUD logic.
 * Custom query methods are generated by Spring Data JPA based on method names.
 */
@Repository
public interface UserRepository extends JpaRepository<User, Long> {

    /**
     * Used for login and JWT generation.
     */
    Optional<User> findByUsername(String username);

    Optional<User> findByEmail(String email);

    /**
     * Existence checks for registration validation.
     * Returns true if a match is found in the 'users' table.
     */
    Boolean existsByUsername(String username);

    Boolean existsByEmail(String email);
}
